
const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";
const GET_PRODUCTS_IN_CARTS = "GET_PRODUCTS_IN_CARTS";
const UPDATE_PRODUCT_LIST = "UPDATE_PRODUCT_LIST";
const UPDATE_PRODUCT = "UPDATE_PRODUCT";
const CHANGE_SORTING_OPTION = "CHANGE_SORTING_OPTION";
const OPEN_DELETE_MODAL = "OPEN_DELETE_MODAL";
const SEND_PRODUCT_ID_IN_CART = "SEND_PRODUCT_ID_IN_CART";

const visibilityTypes = {
    ADD_PRODUCT_TO_CART,
    DELETE_PRODUCT_FROM_CART,
    GET_PRODUCTS_IN_CARTS,
    UPDATE_PRODUCT_LIST,
    UPDATE_PRODUCT,
    CHANGE_SORTING_OPTION,
    OPEN_DELETE_MODAL,
    SEND_PRODUCT_ID_IN_CART
}
export default visibilityTypes